name: Download Prisma IS

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'

  pull_request:
    branches: [ main ]
    
concurrency:
  group: workflow-${{ github.head_ref }}
  cancel-in-progress: true
  
jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
    
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y_%m_%d_%H_%M')"
    
    - name: download prisma_cloud_compute_edition
      run: wget https://cdn.twistlock.com/releases/F1hMvev9/prisma_cloud_compute_edition_31_01_123.tar.gz

    - name: extract prisma_cloud_compute_edition
      run: tar -xvzf prisma_cloud_compute_edition_31_01_123.tar.gz

    - name: get files in a folder
      run: cd linux; ls -lah

    - name: run twistcli intelligence download
      run: ./linux/twistcli intelligence download --token ${{ secrets.TWISTCLI_TOKEN }}

    - name: get files in a folder after download intelligence
      run: ls -lah

    - uses: ncipollo/release-action@v1
      with:
        artifacts: "twistlock_feed*.tar.gz"
        body: |
          twistcli feed download date: ${{ steps.date.outputs.date }}
